Fix the vsphere-xcopy-volume-populator vendors and github build
`make build-vsphere-xcopy-volume-populator-image` fails with:

```
go: google.golang.org/genproto/googleapis/rpc@v0.0.0-20250425173222-7b384671a197: module google.golang.org/genproto/googleapis/rpc@v0.0.0-20250425173222-7b384671a197 requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local)
Error: building at STEP "RUN go mod download && go mod verify": while running runtime: exit status 1
make: *** [Makefile:265: build-vsphere-xcopy-volume-populator-image] Error 1
```

Signed-off-by: Martin Necas <mnecas@redhat.com>